/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      colors: {
        "secondary": "#00e3fd",
        "primary": "#b6a0ff",
        "on-tertiary-container": "#59002e",
        "background": "#0c0e12",
        "inverse-on-surface": "#53555a",
        "on-primary-fixed-variant": "#32008a",
        "surface-container-high": "#1d2025",
        "on-surface": "#f6f6fc",
        "on-error": "#490013",
        "secondary-fixed": "#26e6ff",
        "surface-container-highest": "#23262c",
        "outline": "#74757a",
        "primary-container": "#a98fff",
        "inverse-primary": "#6834eb",
        "surface-container-lowest": "#000000",
        "surface-dim": "#0c0e12",
        "on-primary": "#340090",
        "inverse-surface": "#f9f9ff",
        "secondary-container": "#006875",
        "on-tertiary-fixed-variant": "#70103e",
        "surface-variant": "#23262c",
        "tertiary-fixed": "#ff8db6",
        "surface-container-low": "#111318",
        "on-secondary-fixed": "#003a42",
        "secondary-dim": "#00d4ec",
        "surface-container": "#171a1f",
        "tertiary": "#ff96bb",
        "on-secondary-container": "#e8fbff",
        "tertiary-container": "#fb81ae",
        "on-secondary-fixed-variant": "#005964",
        "primary-fixed": "#a98fff",
        "surface-bright": "#292c33",
        "on-tertiary": "#690939",
        "secondary-fixed-dim": "#00d7f0",
        "on-primary-fixed": "#000000",
        "primary-dim": "#7e51ff",
        "error": "#ff6e84",
        "on-secondary": "#004d57",
        "on-tertiary-fixed": "#37001a",
        "on-error-container": "#ffb2b9",
        "tertiary-dim": "#ee77a3",
        "error-dim": "#d73357",
        "on-background": "#f6f6fc",
        "surface-tint": "#b6a0ff",
        "surface": "#0c0e12",
        "on-surface-variant": "#aaabb0",
        "error-container": "#a70138",
        "on-primary-container": "#280072",
        "tertiary-fixed-dim": "#f57ca9",
        "outline-variant": "#46484d",
        "primary-fixed-dim": "#9c7eff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "2xl": "1rem", "3xl": "1.5rem", "full": "9999px" },
    },
  },
  plugins: [],
};
